# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /serial

# Install any needed packages specified in requirements.txt
COPY ./serial/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /workdir
COPY ./serial .

# Make port 80 available to the world outside this container (Optional, only for web apps)
# EXPOSE 80

# Define environment variable (optional)
ENV NAME World

# Run app.py when the container launches
CMD ["python", "serial_message_router.py"]